# Generated by Django 4.2 on 2025-02-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_liveupdate_stages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdate',
            name='stages_label',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Withheld', 'Withheld'), ('Arrived', 'Arrived')], max_length=50),
        ),
    ]
