# Generated by Django 4.2 on 2025-02-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_liveupdate_stages_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveupdate',
            name='current_location',
        ),
    ]
